config/routes.rb
Rails.application.routes.draw do
  
  get 'lists/new'
  
  get 'top' => 'homes#top'
  
  post 'lists' => 'lists#create'
  
  # get 'lists/index'
  get 'lists' => 'lists#index'
  
  # 基礎知識学習フェーズ/アプリケーションを完成させよう/4章
  # get 'lists/show'
  get 'lists/:id' => 'lists#show', as: 'list'
  
  # 基礎知識学習フェーズ/アプリケーションを完成させよう/5章
  # get 'lists/edit'
  get 'lists/:id/edit' => 'lists#edit', as: 'edit_list'
  
  # 基礎知識学習フェーズ/アプリケーションを完成させよう/5章
  patch 'lists/:id' => 'lists#update', as: 'update_list'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    
    has_one_attached :image
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    
#   基礎知識学習フェーズ/Railsを学ぼう/3章
  def top
  end
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  
  def new
    @list = List.new
  end
  
  def create
    # 基礎知識学習フェーズ/アプリケーションを完成させよう/2章
    list = List.new(list_params)
    list.save
    # 基礎知識学習フェーズ/アプリケーションを完成させよう/4章
    redirect_to list_path(list.id)
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    # 基礎知識学習フェーズ/アプリケーションを完成させよう/5章
    @list = List.find(params[:id])
  end
  
  # 基礎知識学習フェーズ/アプリケーションを完成させよう/5章
  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to list_path(list.id)
  end
  
  private
  
  def list_params
    params.require(:list).permit(:title, :body)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<h3>Topページ</h3>

<!--投稿された漫画の画像表示-->
<!--投稿者名・ユーザー名-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manga</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

            <h1>編集画面</h1>
              <!--基礎知識学習フェーズ/アプリケーションを完成させよう/5章-->
              <%= form_with model: @list, url:update_list_path(@list.id), method: :patch do |f| %>
                
                <h4>タイトル</h4>
                  <%= f.text_field :title %>
                
                <h4>本文</h4>
                  <%= f.text_area :body %>
                
                <%= f.submit '保存' %>
                
              <% end %>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

  <% @lists.each do |list| %>
    
    <p>タイトル</p>
    <span><%= link_to list.title, list_path(list.id) %></span>
    
  <% end %>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>

<!--基礎知識学習フェーズ/アプリケーションを完成させよう/2章-->
<h1>新規投稿</h1>
 <!--form_with部分 -->
<%= form_with model: @list do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  
  <h4>本文</h4>
  <%= f.text_area :body %>
  
  <%= f.submit "投稿する" %>
<% end %>

app/views/lists/show.html.erb
<h1>詳細画面</h1>
<p>Find me in app/views/lists/show.html.erb</p>

  <h2>タイトル</h2>
    <p><%= @list.title %></p>
    
  <h2>本文</h2>
    <p><%= @list.body %></p>
    
  <%= link_to "編集", edit_list_path(@list.id) %>